changelog:
    exclude:
        labels:
            - GitHub Actions

    categories:
        - title: New Features
          labels:
              - Configuration File
              - Core API
              - Command Line Interface
              - Parser
              - 'Plugin API: Extends Config'
              - 'Plugin API: Parser'
              - 'Plugin API: Pretender Hooks'
              - 'Plugin API: Rule'
              - Rule

        - title: Update Specs
          labels:
              - Specs

        - title: Update Presets
          labels:
              - Config Presets

        - title: Update VS Code Extension
          labels:
              - VS Code Extension

        - title: Bug Fixes
          labels:
              - Bug

        - title: Dependency Updates
          labels:
              - Dependencies
