name: VS Code Extension Packaging Test

on:
    pull_request:
        branches:
            - dev
            - v3
        paths:
            - 'vscode/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: yarn vscode:package
