name: VS Code Extension Packaging Test

on:
    pull_request:
        branches:
            - dev
            - v3
        paths:
            - 'vscode/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn vscode:package
