name: VS Code Extension Packaging Test

on:
    pull_request:
        branches:
            - dev
            - v3
        paths:
            - 'vscode/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn vscode:package
