name: VS Code Extension Running Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'vscode/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run tests
              run: cd vscode && yarn vscode:test
